### ISSUE TITLE
Base-64

### ISSUE THREAD

**Issue by avkomar** [Evgenius2020/base64#2]
Евгений, 
исправьте замечания в рамках [этого пулл-реквеста](https://github.com/Evgenius2020/base64/pull/1)
В добавок к замечаниям из пулл-реквеста.
У Вас не реализована опция `-f N` для вставки перевода строки через каждые N символов в режиме кодирования.

**Comment by avkomar** [comment]
@Evgenius2020 

1. код по прежнему не ANSI C и не компилируется. См. мой [коммит](https://github.com/avkomar/base64/commit/2252ece8e2795cf04e511469897c8e0d9be11c39), с изменениями для ANSI C - совместимости.

2. код парсинга командной строки сильно усложнен. В `parseFormatFlag` можно использовать стандартную функцию `atoi`.

3. Нету сообщения об ошибке для пользователя, если декодирование в `NORMAL_DECODE_MODE` и встретился символ не из алфавита. Функция возвращает ошибку, которую никто не обрабатывает, программа молча завершает работу, а пользователь получается считает, что всё хорошо?

**Comment by Evgenius2020** [comment]
https://github.com/avkomar
Исправления выполнены. Отправляю на проверку.

**Comment by avkomar** [comment]
@Evgenius2020 

> "Failure! Decoding has been stoped!"

stoped => stopped :-)

Еще одно замечание на будущее:
- сообщение об ошибке по идее должно включать необходимую информацию о сути ошибки, т.е.  в Вашем случае, это ошибка декодирования, потому что исходном файле (каком? имя файла?), где-то (на какой конкретной позиции?)  встретился символ (с какоим кодом) не из base64 алфавита.

Т.е. например вот такое сообщение об ошибке:
> ERROR: base64 decode failure: unknown symbol with code '19'
> FILE: C:\input.base64
> POSITION: 344

Т.е. пользователь, который сталкивается с этой ошибкой сразу понимает, что случилось и где искать/отлаживать проблему.

Лаб. работа Base64 принята.
